---
- name: Deploy Langflow container on RHEL
  hosts: localhost
  become: yes
  gather_facts: no
  connection: local
  tasks:
    - name: Pull Langflow image
      command: docker pull langflow/langflow:latest

    - name: Stop Langflow container if running
      command: docker stop langflow
      ignore_errors: yes

    - name: Remove existing Langflow container if exists
      command: docker rm langflow
      ignore_errors: yes

    - name: Run Langflow container
      command: >
        docker run -d --name langflow
        -p 7860:7860
        langflow/langflow:latest
